---
# tasks file for desktop
- tasks:
     - name: xfce-desktop
       package: packager=xfce4-desktop state=present
     - name: xfce4-whisker
       package: package=xfce4-whiskermenu-plugin state=present
