---
# tasks file for global_software

- name: add all the packages
  package: name={{ item }} state=present
  with_items:
       - bash-completion
       - debian-goodies
       - dnsutils
       - fail2ban
       - git
       - htop
       - lynis
       - net-tools
       - python-pip
       - python3-pip
       - screen
       - subversion
       - tmux
       - unzip
       - vim
       - wget
       - zip
