---
# tasks file for global_software

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: add all the packages
  apt: name={{ item }} state=present
  with_items:
       - zip
       - unzip
       - wget
       - bash-completion
       - debian-goodies
       - fail2ban
       - lynis
       - tmux
       - git
       - python3-pip
       - python-pip
       - htop
       - vim
